# Generated by Django 5.0.9 on 2025-08-06 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('post_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to='gallery_images/thumbnails/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('marked_for_deletion', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdg.page')),
            ],
        ),
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('image_ids', models.JSONField(blank=True, default=list)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdg.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_number', models.IntegerField(blank=True, choices=[(1, 'No Poverty'), (2, 'Zero Hunger'), (3, 'Good Health and Well-being'), (4, 'Quality Education'), (5, 'Gender Equality'), (6, 'Clean Water and Sanitation'), (7, 'Affordable and Clean Energy'), (8, 'Decent Work and Economic Growth'), (9, 'Industry, Innovation and Infrastructure'), (10, 'Reduced Inequality'), (11, 'Sustainable Cities and Communities'), (12, 'Responsible Consumption and Production'), (13, 'Climate Action'), (14, 'Life Below Water'), (15, 'Life on Land'), (16, 'Peace, Justice and Strong Institutions'), (17, 'Partnerships for the Goals')], null=True)),
                ('category_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdg.page')),
            ],
        ),
    ]
