"""
Django settings for scms project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y#s)a9#9^1(a7*yatqb4l$6(0s9ei#ty#j#t=c1yc6lj1czxr*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'school',
    'accounts',
    'news_updates',
    'event_scheduling',
    'programs',
    'sdg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'scms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scms.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

DATA_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Allow all domains to make requests
# CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://172.16.0.61:8001",
    "http://127.0.0.1:8000",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://172.16.0.61:8001",
    "http://127.0.0.1:8000",
    "http://testweb.hccci.edu.ph",
    "https://testweb.hccci.edu.ph",
    "http://hccci.edu.ph",
    "https://hccci.edu.ph",
]

CORS_ALLOW_CREDENTIALS = True

AUTH_USER_MODEL = 'accounts.CustomUser'

# LOGIN_URL = '/cms/login/'

SESSION_COOKIE_AGE = 7200  # Session will expire after 2 hours (7200 seconds)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Session expires when the browser is closed

# Classify Page
# FACEBOOK_ACCESS_TOKEN = 'EAAONAu4pQfcBO6IJWBtvmI3hNx3Rf1TBsQ7xKQZAmonvVfpWvewBfXaCL1fQXDF26wWJER7BKLJ55gfrOpw8BOQDwcMDMhdztfWkw9SxIHfzsGxE4tdNObWbdsc3ZBVpblwdkZAoodkEDGs0jCSZBMNyrE4I5NkacsiISvw4Rji0lQG1IZCDZBO8ZBDTAry7AbCkRgZD'

# HCCCI Page
FACEBOOK_ACCESS_TOKEN = 'EAAenK1hfFUYBO1grfUq4ExsqcOxKSZCRD0sLKujxi0oi5n1eZCHWvpSw4RYiVCMakgZCLT8xZA3uxk33QtEg98l1ymP0DJ5sZCjuf6MOEi6ocUgpgTYSu47DxWH2vUVv0Yuy7XFh94sdmPydmIml3HcNwjf0beT6wSS628fxafjHf5MASzmQZBBkoWQcsPRdXjaLgZD'