# Generated by Django 5.0.9 on 2025-08-06 07:26

import django.db.models.deletion
import django.utils.timezone
import programs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramsPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('description_img', models.ImageField(blank=True, null=True, upload_to=programs.models.unique_upload_path)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('skills_img', models.ImageField(blank=True, null=True, upload_to=programs.models.unique_upload_path)),
                ('career_opportunities', models.JSONField(blank=True, default=list)),
                ('related_articles', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shs_Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('strand_image', models.ImageField(blank=True, null=True, upload_to=programs.models.unique_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='ShsTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course_image', models.ImageField(blank=True, null=True, upload_to=programs.models.unique_upload_path)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.collegedepartment')),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Pending', max_length=250)),
                ('college_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.collegecourse')),
                ('shs_strand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.shs_strand')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.programs')),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.programspagecontent')),
            ],
        ),
        migrations.AddField(
            model_name='shs_strand',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.shstrack'),
        ),
    ]
